batch_size: 512
beta1: 0.8
beta2: 0.9
beta_max: 20.0
beta_min: 0.1
ch_mult:
- 1
- 2
- 2
class_num: 2
configs_file: .\configs\configs_binary.yaml
dataset: coil_2000
device: cuda:0
exp: exp0
feature_len: 85
init_ch: 16
lazy_reg: null
lr_d: 0.002
lr_g: 0.005
ngf: 32
num_channels: 1
num_epoch: 800
num_timesteps: 4
nz: 50
pw1: 1
pw2: 1
r1_gamma: 0.05
rbg: 4
resume: false
save_ckpt_every: 50
save_configs: true
save_content: false
save_content_every: 50
seed: 2
t_emb_dim: 32
use_configs: false
use_geometric: false
